### ISSUE TITLE
add ability to sort vendor's list on vendor-list.html

### ISSUE THREAD

**Issue by CatherineEvelyn** [CatherineEvelyn/wedding-planner#49] opened 2017-10-13 23:04 UTC
## Problem
user should be able to sort or filter the vendor's list by location (state and/or zipcode), rating(optional, we could skip rating feature if there isn't enough time), min price, or max price.
This is a feature, so I didn't put high priority on this issue.

## Details
* **Related Issues:** #40 #41 #42 
* **Role:** Back end

**Comment by Zafuzi** [comment] 2017-10-25 18:02
Closed as it's a duplicate of issue #58

**Closed as completed by Zafuzi** 2017-10-25 18:02 UTC
Labels: priority: 2 medium
